### ISSUE TITLE
Ivy dashboard datasources will not populate

### ISSUE THREAD

**Issue by daflad** [ivylabs/IvyDD#1]
The list of datasources will not populate and as mentioned previously I have installed cda & Saiku.

**Comment by latinojoel** [comment]
Hi @daflad,

IvyDD just works with saiku files on **admin** folder. Is that your issue?

Cheers
@latinojoel

**Comment by daflad** [comment]
Hi @latinojoel,

Thank you for your quick response, Saiku file now saved to the admin folder, server shut down and restarted but still nothing in the list of files.

Any other thoughts?

Regards,

@daflad

**Comment by latinojoel** [comment]
Hi @daflad,

Do you can provide some logs? From the server and/or Firebug (or other client)?
Which Saiku version and CDA version you're using?

Thanks.
@latinojoel

**Comment by daflad** [comment]
Hi,

logfiles added to open repo: https://github.com/daflad/logfiles

chrome inspector throws the following error / warning

Object {username: "AdminSteve", roles: Array[5], language: "en", sessionid: "546c10c4-6b6d-443c-b4f4-9b00cf1edf75"} VM3783:1
Invalid App Id: Must be a number or numeric string representing the application id. sdk.js:56
Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 1.5), (min-resolution: 144dpi) tweet_button.1410542722.html:1
Uncaught TypeError: Cannot read property 'e' of null 7F189578EC75716F930C264F9194C03A.cache.html:2275

Thanks in advance

Stephen

**Comment by daflad** [comment]
Sorry missed some info:

CDA Version: 14.07.29 (STABLE)

Saiku Version: just says trunk.  Will not let me install 2.6 stable just errors out each time

**Comment by latinojoel** [comment]
@daflad Saiku trunk will be the new Saiku 3.0. And I can not support trunk versions will be a hard work. Try download the saiku 2.6 plugin from this page: http://meteorite.bi/saiku/download.
For install you just need delete the **saiku** folder on pentaho-solution/system/saiku and then unzip the plugin in the **system** folder.

I hope that works for you.
Cheers.

**Comment by daflad** [comment]
@latinojoel I've tried a fresh install of pentaho 5 with saiku 2.6 & cda 14.07.29 but still no joy.  I have updated the previously mentioned repo with the logs from this new instance.  If you have any suggestions on which way to go next that would be great.

Cheers

**Comment by latinojoel** [comment]
Hi @daflad,

Sorry for the delay. 
I did a update recently in the Pentaho marketplace and the plugin was completely reviewed in a Windows and Ubuntu machine for Pentaho CE.
Seems you're using a EE version, right? If that's ok, is possible make a quick test in the same machine with Pentaho CE?
The unique error related with the plugin, I can see, is the javascript one but that just exist for EE.

Cheers
@latinojoel
