### ISSUE TITLE
Error creating analysis.

### ISSUE THREAD

**Issue by mlino** [ivylabs/IvyDD#3]
Hi,

I'm trying to use ivy DD to create a dashboard with a saiku analysis file, but I always got the following error message a few seconds after hit OK button.

Error: Error.

I'm using pentaho CE 5.2 and Saiku 3.0 installed from Pentaho Marketplace.

Regards,

Marcio

**Comment by latinojoel** [comment]
Hi @mlino , isn't prepared for work with saiku 3. Just works with 2.6...

Cheers.

**Comment by mlino** [comment]
Thanks @latinojoel I will try with saiku 2.6.
